export const primary = {
  'INCOME': {name: 'Income', icon: '💰'},
  'TRANSFER_IN': {name: 'Transfer In', icon: '💸'},
  'TRANSFER_OUT': {name: 'Transfer Out', icon: '💸'},
  'LOAN_PAYMENTS': {name: 'Payments', icon: '🏦'},
  'BANK_FEES': {name: 'Bank Fees', icon: '🏦'},
  'ENTERTAINMENT': {name: 'Entertainment', icon: '🎉'},
  'FOOD_AND_DRINK': {name: 'Food & Drink', icon: '🍔'},
  'GENERAL_MERCHANDISE': {name: 'Merchandise', icon: '👖'},
  'HOME_IMPROVEMENT': {name: 'Home Improvement', icon: '🔨'},
  'MEDICAL': {name: 'Medical', icon: '🚑'},
  'PERSONAL_CARE': {name: 'Self Care', icon: '💆'},
  'GENERAL_SERVICES': {name: 'Services', icon: '💸'},
  'TRANSPORTATION': {name: 'Transportation', icon: '🚗'},
  'TRAVEL': {name: 'Travel', icon: '🌎'},
  'RENT_AND_UTILITIES': {name: 'Rent & Utilities', icon: '🏡'},
  'GOVERNMENT_AND_NON_PROFIT': {name: "Gov't & Non-Profit", icon: '🏛️'},
}